### PR TITLE
Change "invite" to "invitation" (text only, not filenames)

### PR DESCRIPTION
**Pull request by troy**
Fix a grammar [bug](http://bekahcubed.menterz.com/blog/2010/20101004-5274.htm) before anyone else falls victim to it.

### CODE REVIEW

**Comment by troy** [comment]
@gschier, anything I can do to make this more merge-worthy or easier for you to review? Happy to do my part to save you time, or try to :)

**Comment by troy** [comment]
ping :) This should be safe to merge as-is.

**Comment by demoore** [comment]
@troy thanks for poking us. Our grammar be no good.

**Comment by troy** [comment]
:+1: 

gr

**Pull request merged**
